logging:
  level:
    root: INFO
    com:
      zaxxer:
        hikari:
          pool: ERROR
spring:
  jpa:
    hibernate:
      ddl-auto: update  # create will recreate the tables... use `update` instead create
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/dars_webcrawler?useSSL=true
    username: root
    password:

# crawler configuration
crawler:
  # minimum waiting time between crawls from the same site (in milliseconds)
  site-wait-time-min: 1000
  # maximum waiting time between crawls from the same site (in milliseconds)
  site-wait-time-max: 2000
  # path to the file containing the crawler seed list
  gecko-driver-filename: geckodriver.exe

# configuration of RetrievalCore API access
retrievalcore-api:
  server: http://localhost:5678
  authentication-path: /api/auth/signin
  username: crawler1
  password: $#%#$#$$^$Y$Y$Yh56h56h5^H%^JH%j56j^&J67j67J67j34t#$34tG54
